kind: ConfigMap
apiVersion: v1
metadata:
  name: static-as3-definition
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "remove configmap",
            "static": {
                "class": "Tenant"
            }
        }
    }