kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-tcp-declaration
  namespace: test2-icni-1
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "service-tcp",
            "TCP": {
                "class": "Tenant",
                "tcp_app": {
                    "class": "Application",
                    "template": "generic",
                    "VS_tcp": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            "10.75.70.6"
                        ],
                        "virtualPort": 22,
                        "pool": "tcp_app_pool"
                    },
                    "tcp_app_pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 22,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
