kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-nat46-declaration
  namespace: nat46
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "snat_pool_for_NAT46",
            "NAT_46": {
                "class": "Tenant",
                "NAT_46_app": {
                    "class": "Application",
                    "template": "generic",
                    "VS_IPv6_Serving": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            "fd6a:18ea:ca6d:c::10"
                        ],
                        "virtualPort": 80,
                        "pool": "NAT_46_app_pool"
                    },
                    "NAT_46_app_pool": {
                        "class": "Pool",
                        "monitors": [
                            "tcp"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
