kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
labels:
  f5type: virtual-server
  overrideAS3: "true"
data:
  template: |
    {
        "declaration": {
            "ocp_AS3": {
                "Shared": {
                    "Ingress_10_1_10_12_80": {
                        "securityLogProfiles": [
                            {
                                "bigip": "/Common/Log all requests"
                            }
                        ],
                        "policyWAF": {
                            "bigip": "/Common/linux-low"
                        }
                    }
                }
            }
        }
    }