apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
      virtual-server.f5.com/ip: 10.192.75.108
    name: argocd-http
    namespace: default
  spec:
    rules:
    - host: mysite.f5demo.com
      http:
        paths:
        - backend:
            serviceName: f5-hello-world
            servicePort: 80